export enum CarCategory {
    Micro = 'Micro',
    Sedan = 'Sedan',
    CUV = 'CUV',
    SUV = 'SUV',
    Hatchback = 'Hatchback',
    Roadster = 'Roadster',
    Pickup = 'Pickup',
    Van = 'Van',
    Coupe = 'Coupe',
    SuperCar = 'SuperCar',
    CamperVAN = 'CamperVAN',
    MiniTruck = 'MiniTruck',
    Cabriolet = 'Cabriolet',
    MiniVAN = 'MiniVAN',
    Truck = 'Truck',
    BigTruck = 'BigTruck',
}
